version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.0
    ports:
      - "5000:5000"
    command: >
      mlflow server --host 0.0.0.0 --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlruns
    volumes:
      - ./mlruns:/mlruns
