name: CI/CD Pipeline - Titanic API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      # Run tests (optional)
      - name: Run tests
        run: |
          echo "No tests yet"
          # pytest tests/

      # Log in to GitHub Container Registry using PAT
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Set lowercase repository name
      - name: Set lowercase repo name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_LC }}/titanic-api:latest .

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_LC }}/titanic-api:latest



  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to remote VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.repository }}/titanic-api:latest
            docker stop titanic-api || true
            docker rm titanic-api || true
            docker run -d --name titanic-api -p 8000:8000 ghcr.io/${{ github.repository }}/titanic-api:latest